-- ================================================================
-- ANNOUNCEMENTS TABLE
-- ================================================================
-- Table for managing campus-wide announcements with theme and language support

CREATE TABLE IF NOT EXISTS public.announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  content text NOT NULL,
  theme text NOT NULL DEFAULT 'default',
  language text NOT NULL DEFAULT 'en',
  priority text NOT NULL DEFAULT 'medium',
  target_audience text NOT NULL DEFAULT 'all',
  is_active boolean DEFAULT true,
  created_by text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  expires_at timestamp with time zone,
  CONSTRAINT valid_theme CHECK (theme IN ('default', 'info', 'success', 'warning', 'danger', 'gradient')),
  CONSTRAINT valid_language CHECK (language IN ('en', 'hi', 'gu', 'es', 'fr', 'de')),
  CONSTRAINT valid_priority CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  CONSTRAINT valid_audience CHECK (target_audience IN ('all', 'students', 'faculty', 'admin'))
) TABLESPACE pg_default;

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_announcements_active ON public.announcements USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_announcements_audience ON public.announcements USING btree (target_audience);
CREATE INDEX IF NOT EXISTS idx_announcements_priority ON public.announcements USING btree (priority);
CREATE INDEX IF NOT EXISTS idx_announcements_created_at ON public.announcements USING btree (created_at);

-- Comments
COMMENT ON TABLE public.announcements IS 'Campus-wide announcements with multi-theme and multi-language support';
COMMENT ON COLUMN public.announcements.theme IS 'Visual theme: default, info, success, warning, danger, gradient';
COMMENT ON COLUMN public.announcements.language IS 'Content language: en, hi, gu, es, fr, de';
COMMENT ON COLUMN public.announcements.priority IS 'Display priority: low, medium, high, urgent';
COMMENT ON COLUMN public.announcements.target_audience IS 'Target audience: all, students, faculty, admin';
COMMENT ON COLUMN public.announcements.expires_at IS 'Optional expiration date for time-sensitive announcements';
