-- ================================================================
-- REPORT CONFIGURATION TABLES
-- ================================================================
-- Tables for managing dynamic report form fields

-- Report Field Configuration Table
CREATE TABLE IF NOT EXISTS public.report_field_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_name text NOT NULL UNIQUE,
  field_label text NOT NULL,
  field_type text NOT NULL,
  options jsonb DEFAULT '[]'::jsonb,
  is_required boolean DEFAULT true,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT valid_field_type CHECK (field_type IN ('text', 'textarea', 'select', 'multiselect', 'number', 'file'))
) TABLESPACE pg_default;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_report_field_config_active ON public.report_field_config USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_report_field_config_order ON public.report_field_config USING btree (display_order);

-- Comments
COMMENT ON TABLE public.report_field_config IS 'Configuration for dynamic report form fields';
COMMENT ON COLUMN public.report_field_config.field_name IS 'Internal field name (e.g., Problem_Category)';
COMMENT ON COLUMN public.report_field_config.field_label IS 'Display label for the field';
COMMENT ON COLUMN public.report_field_config.field_type IS 'Field input type';
COMMENT ON COLUMN public.report_field_config.options IS 'JSON array of options for select/multiselect fields';

-- Insert default configuration
INSERT INTO public.report_field_config (field_name, field_label, field_type, options, is_required, display_order) VALUES
('Problem_Category', 'Problem Category', 'select', '["Infrastructure", "IT/Technical", "Academic", "Administrative", "Safety/Security", "Maintenance"]', true, 1),
('Institute', 'Institute', 'select', '["CHARUSAT", "CSPIT", "DEPSTAR", "CMPICA", "Other"]', true, 2),
('Location', 'Location', 'select', '["Class", "Lab", "Center Square", "Hall", "Institute", "Hostel", "Cafeteria", "Library", "Sports Ground", "Parking"]', true, 3),
('class_No', 'Class/Room Number', 'text', '[]', false, 4),
('Impact_Scope', 'Impact Scope', 'select', '["Single person affected", "Whole class affected", "Everyone affected"]', true, 5),
('Occurrence_Pattern', 'Occurrence Pattern', 'select', '["First occurrence", "Recurring issue", "Daily", "Weekly"]', true, 6),
('Description', 'Description', 'textarea', '[]', true, 7),
('Photo', 'Photos', 'file', '[]', false, 8)
ON CONFLICT (field_name) DO NOTHING;

-- Category weights table for ML model
CREATE TABLE IF NOT EXISTS public.category_weights (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL UNIQUE,
  weight integer NOT NULL DEFAULT 1,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
) TABLESPACE pg_default;

-- Insert default category weights
INSERT INTO public.category_weights (category, weight) VALUES
('Infrastructure', 2),
('IT/Technical', 2),
('Academic', 1),
('Administrative', 1),
('Safety/Security', 3),
('Maintenance', 2)
ON CONFLICT (category) DO NOTHING;

-- Impact weights table
CREATE TABLE IF NOT EXISTS public.impact_weights (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  impact_scope text NOT NULL UNIQUE,
  weight integer NOT NULL DEFAULT 1,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
) TABLESPACE pg_default;

-- Insert default impact weights
INSERT INTO public.impact_weights (impact_scope, weight) VALUES
('Single person affected', 1),
('Whole class affected', 2),
('Everyone affected', 3)
ON CONFLICT (impact_scope) DO NOTHING;

-- Occurrence weights table
CREATE TABLE IF NOT EXISTS public.occurrence_weights (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurrence_pattern text NOT NULL UNIQUE,
  weight integer NOT NULL DEFAULT 1,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
) TABLESPACE pg_default;

-- Insert default occurrence weights
INSERT INTO public.occurrence_weights (occurrence_pattern, weight) VALUES
('First occurrence', 1),
('Recurring issue', 2),
('Daily', 3),
('Weekly', 2)
ON CONFLICT (occurrence_pattern) DO NOTHING;
